name: Generate SVG Animations

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight
  workflow_dispatch: # allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Pacman contribution graph
      - name: Generate Pacman graph
        uses: Platane/snk@v3
        with:
          github_user_name: Biprotosh
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Snake graph (if you also want it)
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Biprotosh
          outputs: dist/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
